# Application
spring.application.name=shareit-gateway
server.port=8080

# Server URL - ??? Docker ?????????? ??? ??????????
shareit-server.url=http://shareit-server:9090

# Validation
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.ru.practicum.shareit=INFO
logging.level.org.springframework.web=WARN